version: '3'

services:

  jenkins:
    image: local/jenkins-distribution
    build: ./
    ports:
      - 8080:8080
      - 50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.yaml:/cfg/jenkins.yaml
    environment:
      CASC_JENKINS_CONFIG: /cfg/jenkins.yaml
      PLUGINS_FORCE_UPGRADE: 'true'
      JAVA_OPTS: >-
          -Dhudson.TcpSlaveAgentListener.hostName=jenkins
          -Dhudson.TcpSlaveAgentListener.port=50000
          -Djenkins.install.runSetupWizard=false
          -Djenkins.security.ManagePermission=true
          -Djenkins.security.SystemReadPermission=true
          -Dhudson.security.ExtendedReadPermission=true
# jenkins.ui.refresh 