name: update jenkins version

on:
  workflow_dispatch:
  schedule:
  - cron: "30 21 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: update for jenkins version
      id: jenkins-version
      uses: addnab/docker-run-action@v3
      with:
        image: jenkins/jenkins:lts-jdk11
        options: -u root -v ${{ github.workspace }}:/src
        shell: bash
        run: |
          echo "JENKINS VERSION: ${JENKINS_VERSION}"
          sed -ie "s|FROM jenkins/jenkins:.*|FROM jenkins/jenkins:${JENKINS_VERSION}-jdk11|" /src/Dockerfile
          echo "::set-output name=version::$JENKINS_VERSION"

    - name: get git diff
      id: git-diff
      run: echo "::set-output name=dockerfile::$(git --no-pager diff --name-only | grep Dockerfile)"

    - name: create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: latest/jenkins-lts
        commit-message: automated Jenkins lts version update
        add-paths: |
          Dockerfile
        committer: base2bot <noreply@base2services.com>
        delete-branch: true
        title: Jenkins lts version update
        body: |
          ${{ steps.jenkins-version.outputs.version }}
        labels: |
          latest-jenkin-lts
          jenkins-distribution
      if: steps.git-diff.outputs.dockerfile

