name: update jenkins plugins

on:
  push:
    branches:
      - feature/gh-action-plugin-updater
  schedule:
      - cron: "0 8 * * 1"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDDHHmm

    - name: checkout new branch
      run: |
        git checkout -b plugin-updates-${{ steps.current-time.outputs.formattedTime }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Container Image
      uses: docker/build-push-action@v2
      with:
        tags: local/jenkins-distribution:latest
        push: false
        load: true

    - name: check for plugin updates
      uses: addnab/docker-run-action@v3
      with:
        image: local/jenkins-distribution:latest
        run: jenkins-plugin-cli --available-updates --plugin-file plugins.yaml --output yaml > plugins.yaml

    - name: check plugin.yaml diff
      id: git-diff
      uses: technote-space/get-diff-action@v6
      with:
        FILES: |
          plugins.yaml

    - name: commit and push any plugin changes
      run: |
        git add plugins.yaml
        git commit -m 'automated plugin updates'
        git push origin plugin-updates-${{ steps.current-time.outputs.formattedTime }}
      if: steps.git-diff.outputs.diff