name: build image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Container Image
      uses: docker/build-push-action@v2
      with:
        tags: local/jenkins-distribution:latest
        push: false
        load: true
    
    - name: Scan image
      uses: anchore/scan-action@v2
      with:
        image: "local/jenkins-distribution:latest"
