name: release docker image

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Container Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to  GitHub Container Repository
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PUSH_TOKEN }}

    - name: Build and push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/base2services/jenkins-distribution:${{ github.event.release.tag_name }},ghcr.io/base2services/jenkins-distribution:lts
